WARNING || 2020-09-18 12:58:59,436 || log || Not Found: /static/debug_toolbar/css/toolbar.css
WARNING || 2020-09-18 12:58:59,595 || log || Not Found: /static/debug_toolbar/js/toolbar.js
WARNING || 2020-09-18 12:58:59,681 || log || Not Found: /static/debug_toolbar/img/ajax-loader.gif
WARNING || 2020-09-18 13:01:05,263 || log || Not Found: /static/rest_framework/css/bootstrap.min.css
WARNING || 2020-09-18 13:01:05,372 || log || Not Found: /static/rest_framework/js/jquery-3.4.1.min.js
WARNING || 2020-09-18 13:01:05,427 || log || Not Found: /static/debug_toolbar/css/toolbar.css
WARNING || 2020-09-18 13:01:05,499 || log || Not Found: /static/rest_framework/css/bootstrap-tweaks.css
WARNING || 2020-09-18 13:01:05,560 || log || Not Found: /static/rest_framework/css/prettify.css
WARNING || 2020-09-18 13:01:05,625 || log || Not Found: /static/rest_framework/css/default.css
WARNING || 2020-09-18 13:01:05,716 || log || Not Found: /static/rest_framework/js/ajax-form.js
WARNING || 2020-09-18 13:01:05,800 || log || Not Found: /static/rest_framework/js/csrf.js
WARNING || 2020-09-18 13:01:05,856 || log || Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING || 2020-09-18 13:01:05,911 || log || Not Found: /static/rest_framework/js/prettify-min.js
WARNING || 2020-09-18 13:01:05,967 || log || Not Found: /static/rest_framework/js/default.js
WARNING || 2020-09-18 13:01:06,025 || log || Not Found: /static/debug_toolbar/js/toolbar.js
WARNING || 2020-09-18 13:01:06,083 || log || Not Found: /static/rest_framework/js/jquery-3.4.1.min.js
WARNING || 2020-09-18 13:01:06,144 || log || Not Found: /static/debug_toolbar/img/ajax-loader.gif
WARNING || 2020-09-18 13:01:06,216 || log || Not Found: /static/rest_framework/js/ajax-form.js
WARNING || 2020-09-18 13:01:06,294 || log || Not Found: /static/rest_framework/js/csrf.js
WARNING || 2020-09-18 13:01:06,373 || log || Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING || 2020-09-18 13:01:06,450 || log || Not Found: /static/rest_framework/js/prettify-min.js
WARNING || 2020-09-18 13:01:06,568 || log || Not Found: /static/rest_framework/js/default.js
WARNING || 2020-09-18 13:01:06,634 || log || Not Found: /static/debug_toolbar/css/print.css
WARNING || 2020-09-18 13:01:06,700 || log || Not Found: /static/debug_toolbar/css/toolbar.css
WARNING || 2020-09-18 13:01:06,796 || log || Not Found: /static/debug_toolbar/img/ajax-loader.gif
WARNING || 2020-09-18 13:01:06,865 || log || Not Found: /static/debug_toolbar/js/toolbar.js
WARNING || 2020-09-18 13:54:02,768 || log || Not Found: /static/rest_framework/css/bootstrap.min.css
WARNING || 2020-09-18 13:54:02,884 || log || Not Found: /static/rest_framework/css/bootstrap-tweaks.css
WARNING || 2020-09-18 13:54:02,957 || log || Not Found: /static/rest_framework/css/prettify.css
WARNING || 2020-09-18 13:54:03,037 || log || Not Found: /static/rest_framework/css/default.css
WARNING || 2020-09-18 13:54:03,123 || log || Not Found: /static/rest_framework/js/ajax-form.js
WARNING || 2020-09-18 13:54:03,185 || log || Not Found: /static/rest_framework/js/jquery-3.4.1.min.js
WARNING || 2020-09-18 13:54:03,249 || log || Not Found: /static/debug_toolbar/css/toolbar.css
WARNING || 2020-09-18 13:54:03,312 || log || Not Found: /static/rest_framework/js/csrf.js
WARNING || 2020-09-18 13:54:03,371 || log || Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING || 2020-09-18 13:54:03,433 || log || Not Found: /static/rest_framework/js/prettify-min.js
WARNING || 2020-09-18 13:54:03,492 || log || Not Found: /static/rest_framework/js/default.js
WARNING || 2020-09-18 13:54:03,551 || log || Not Found: /static/debug_toolbar/js/toolbar.js
WARNING || 2020-09-18 13:54:03,611 || log || Not Found: /static/rest_framework/js/ajax-form.js
WARNING || 2020-09-18 13:54:03,668 || log || Not Found: /static/debug_toolbar/img/ajax-loader.gif
WARNING || 2020-09-18 13:54:03,721 || log || Not Found: /static/rest_framework/js/csrf.js
WARNING || 2020-09-18 13:54:03,796 || log || Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING || 2020-09-18 13:54:03,861 || log || Not Found: /static/rest_framework/js/prettify-min.js
WARNING || 2020-09-18 13:54:03,925 || log || Not Found: /static/rest_framework/js/default.js
WARNING || 2020-09-18 13:54:04,006 || log || Not Found: /static/debug_toolbar/css/print.css
WARNING || 2020-09-18 13:54:04,063 || log || Not Found: /static/debug_toolbar/css/toolbar.css
WARNING || 2020-09-18 13:54:04,147 || log || Not Found: /static/debug_toolbar/js/toolbar.js
WARNING || 2020-09-18 13:54:04,229 || log || Not Found: /static/debug_toolbar/img/ajax-loader.gif
WARNING || 2020-09-18 13:56:11,073 || log || Not Found: /static/rest_framework/css/bootstrap.min.css
WARNING || 2020-09-18 13:56:11,168 || log || Not Found: /static/rest_framework/css/bootstrap-tweaks.css
WARNING || 2020-09-18 13:56:11,234 || log || Not Found: /static/rest_framework/css/default.css
WARNING || 2020-09-18 13:56:11,312 || log || Not Found: /static/rest_framework/css/prettify.css
WARNING || 2020-09-18 13:56:11,380 || log || Not Found: /static/rest_framework/js/ajax-form.js
WARNING || 2020-09-18 13:56:11,448 || log || Not Found: /static/rest_framework/js/jquery-3.4.1.min.js
WARNING || 2020-09-18 13:56:11,508 || log || Not Found: /static/debug_toolbar/css/toolbar.css
WARNING || 2020-09-18 13:56:11,562 || log || Not Found: /static/rest_framework/js/csrf.js
WARNING || 2020-09-18 13:56:11,624 || log || Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING || 2020-09-18 13:56:11,676 || log || Not Found: /static/rest_framework/js/prettify-min.js
WARNING || 2020-09-18 13:56:11,728 || log || Not Found: /static/rest_framework/js/default.js
WARNING || 2020-09-18 13:56:11,787 || log || Not Found: /static/debug_toolbar/js/toolbar.js
WARNING || 2020-09-18 13:56:11,892 || log || Not Found: /static/rest_framework/js/ajax-form.js
WARNING || 2020-09-18 13:56:11,952 || log || Not Found: /static/debug_toolbar/img/ajax-loader.gif
WARNING || 2020-09-18 13:56:12,009 || log || Not Found: /static/rest_framework/js/csrf.js
WARNING || 2020-09-18 13:56:12,076 || log || Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING || 2020-09-18 13:56:12,147 || log || Not Found: /static/rest_framework/js/prettify-min.js
WARNING || 2020-09-18 13:56:12,210 || log || Not Found: /static/rest_framework/js/default.js
WARNING || 2020-09-18 13:56:12,310 || log || Not Found: /static/debug_toolbar/css/print.css
WARNING || 2020-09-18 13:56:12,375 || log || Not Found: /static/debug_toolbar/css/toolbar.css
WARNING || 2020-09-18 13:56:12,483 || log || Not Found: /static/debug_toolbar/js/toolbar.js
WARNING || 2020-09-18 13:56:12,565 || log || Not Found: /static/debug_toolbar/img/ajax-loader.gif
WARNING || 2020-09-18 14:04:04,297 || log || Not Found: /static/rest_framework/js/ajax-form.js
WARNING || 2020-09-18 14:04:04,394 || log || Not Found: /static/rest_framework/css/default.css
WARNING || 2020-09-18 14:04:04,459 || log || Not Found: /static/rest_framework/css/bootstrap-tweaks.css
WARNING || 2020-09-18 14:04:04,520 || log || Not Found: /static/rest_framework/js/jquery-3.4.1.min.js
WARNING || 2020-09-18 14:04:04,585 || log || Not Found: /static/rest_framework/css/bootstrap.min.css
WARNING || 2020-09-18 14:04:04,659 || log || Not Found: /static/rest_framework/css/prettify.css
WARNING || 2020-09-18 14:04:04,728 || log || Not Found: /static/debug_toolbar/css/toolbar.css
WARNING || 2020-09-18 14:04:04,787 || log || Not Found: /static/rest_framework/js/csrf.js
WARNING || 2020-09-18 14:04:04,842 || log || Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING || 2020-09-18 14:04:04,901 || log || Not Found: /static/rest_framework/js/prettify-min.js
WARNING || 2020-09-18 14:04:04,960 || log || Not Found: /static/rest_framework/js/default.js
WARNING || 2020-09-18 14:04:05,013 || log || Not Found: /static/debug_toolbar/js/toolbar.js
WARNING || 2020-09-18 14:04:05,072 || log || Not Found: /static/rest_framework/js/jquery-3.4.1.min.js
WARNING || 2020-09-18 14:04:05,137 || log || Not Found: /static/debug_toolbar/img/ajax-loader.gif
WARNING || 2020-09-18 14:04:05,190 || log || Not Found: /static/rest_framework/js/ajax-form.js
WARNING || 2020-09-18 14:04:05,271 || log || Not Found: /static/rest_framework/js/csrf.js
WARNING || 2020-09-18 14:04:05,333 || log || Not Found: /static/rest_framework/js/bootstrap.min.js
WARNING || 2020-09-18 14:04:05,403 || log || Not Found: /static/rest_framework/js/prettify-min.js
WARNING || 2020-09-18 14:04:05,519 || log || Not Found: /static/rest_framework/js/default.js
WARNING || 2020-09-18 14:04:05,619 || log || Not Found: /static/debug_toolbar/css/print.css
WARNING || 2020-09-18 14:04:05,678 || log || Not Found: /static/debug_toolbar/css/toolbar.css
WARNING || 2020-09-18 14:04:05,757 || log || Not Found: /static/debug_toolbar/js/toolbar.js
WARNING || 2020-09-18 14:04:05,835 || log || Not Found: /static/debug_toolbar/img/ajax-loader.gif
WARNING || 2020-09-18 14:15:37,841 || log || Not Found: /administration/history/tvseriesmodel/158/95/
WARNING || 2020-09-18 14:20:10,678 || log || Not Found: /administration/history/tvseriesmodel/158/95/
WARNING || 2020-09-18 14:21:18,094 || log || Not Found: /administration/history/tvseriesmodel/158/95/
ERROR || 2020-09-18 17:39:00,644 || log || Internal Server Error: /admin/users/user/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 202, in _get_response
    response = response.render()
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\templatetags\static.py", line 106, in render
    url = self.url(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\templatetags\static.py", line 103, in url
    return self.handle_simple(path)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\templatetags\static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\contrib\staticfiles\storage.py", line 147, in url
    return self._url(self.stored_name, name, force)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\contrib\staticfiles\storage.py", line 126, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\contrib\staticfiles\storage.py", line 417, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'admin/css/base.css'
ERROR || 2020-09-18 17:39:00,674 || basehttp || "GET /admin/users/user/ HTTP/1.1" 500 145
ERROR || 2020-09-18 17:39:02,832 || log || Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 202, in _get_response
    response = response.render()
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\templatetags\static.py", line 106, in render
    url = self.url(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\templatetags\static.py", line 103, in url
    return self.handle_simple(path)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\templatetags\static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\contrib\staticfiles\storage.py", line 147, in url
    return self._url(self.stored_name, name, force)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\contrib\staticfiles\storage.py", line 126, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\contrib\staticfiles\storage.py", line 417, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'admin/css/base.css'
ERROR || 2020-09-18 17:39:02,844 || basehttp || "GET /admin/ HTTP/1.1" 500 145
ERROR || 2020-09-18 17:39:30,037 || log || Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 202, in _get_response
    response = response.render()
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\templatetags\static.py", line 106, in render
    url = self.url(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\templatetags\static.py", line 103, in url
    return self.handle_simple(path)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\templatetags\static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\contrib\staticfiles\storage.py", line 147, in url
    return self._url(self.stored_name, name, force)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\contrib\staticfiles\storage.py", line 126, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\contrib\staticfiles\storage.py", line 417, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'admin/css/base.css'
ERROR || 2020-09-18 17:39:30,063 || basehttp || "GET /admin/ HTTP/1.1" 500 145
ERROR || 2020-09-18 17:39:31,190 || log || Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 202, in _get_response
    response = response.render()
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\templatetags\static.py", line 106, in render
    url = self.url(context)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\templatetags\static.py", line 103, in url
    return self.handle_simple(path)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\templatetags\static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\contrib\staticfiles\storage.py", line 147, in url
    return self._url(self.stored_name, name, force)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\contrib\staticfiles\storage.py", line 126, in _url
    hashed_name = hashed_name_func(*args)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\contrib\staticfiles\storage.py", line 417, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'admin/css/base.css'
ERROR || 2020-09-18 17:39:31,201 || basehttp || "GET /admin/ HTTP/1.1" 500 145
WARNING || 2020-09-18 17:52:33,146 || log || Bad Request: /auth/users/confirm_undelete_account/
WARNING || 2020-09-18 17:52:33,897 || log || Bad Request: /auth/users/
WARNING || 2020-09-18 17:52:33,936 || log || Bad Request: /auth/users/
WARNING || 2020-09-18 17:52:33,980 || log || Bad Request: /auth/users/
WARNING || 2020-09-18 17:52:34,304 || log || Bad Request: /auth/users/
WARNING || 2020-09-18 17:52:34,344 || log || Bad Request: /auth/users/
WARNING || 2020-09-18 17:52:34,894 || log || Bad Request: /auth/jwt/create
WARNING || 2020-09-18 17:52:35,254 || log || Forbidden: /auth/users/master_slave_interchange/
WARNING || 2020-09-18 17:52:36,186 || log || Too Many Requests: /auth/users/master_slave_interchange/
WARNING || 2020-09-18 17:52:36,445 || log || Bad Request: /auth/users/master_slave_interchange/
WARNING || 2020-09-18 17:52:36,639 || log || Bad Request: /auth/jwt/refresh
WARNING || 2020-09-18 17:52:36,684 || log || Unauthorized: /auth/jwt/refresh
WARNING || 2020-09-18 17:52:37,234 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-18 17:52:37,717 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-18 17:52:38,191 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-18 17:52:38,298 || log || Forbidden: /auth/users/resend_activation/
WARNING || 2020-09-18 17:52:38,332 || log || Forbidden: /auth/users/resend_activation/
WARNING || 2020-09-18 17:52:38,421 || log || Too Many Requests: /auth/users/resend_activation/
WARNING || 2020-09-18 17:52:38,993 || log || Too Many Requests: /auth/users/undelete_account/
WARNING || 2020-09-18 17:52:39,474 || log || Bad Request: /auth/users/undelete_account/
WARNING || 2020-09-19 07:31:14,312 || log || Not Found: /administration/history/tvseriesmodel/158/95/
WARNING || 2020-09-19 07:32:02,937 || log || Not Found: /auth/usgbbt/
WARNING || 2020-09-19 09:22:33,736 || log || Forbidden: /auth/users/me/
WARNING || 2020-09-19 09:34:38,799 || log || Not Found: /auth/users/rtrtrt/
WARNING || 2020-09-19 09:34:47,471 || log || Not Found: /auth/usersggg
WARNING || 2020-09-19 09:56:50,577 || log || Not Found: /favicon.ico
WARNING || 2020-09-19 11:17:58,155 || log || Not Found: /favicon.ico
WARNING || 2020-09-19 12:39:49,591 || log || Bad Request: /archives/tvseries/full-text-search/
ERROR || 2020-09-19 12:39:54,971 || log || Internal Server Error: /archives/tvseries/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 264, in data
    self._data = self.get_initial()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 410, in get_initial
    return OrderedDict([
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 411, in <listcomp>
    (field.field_name, field.get_initial())
  File "/usr/local/lib/python3.8/site-packages/drf_extra_fields/fields.py", line 231, in get_initial
    return self.to_representation(initial)
  File "/usr/local/lib/python3.8/site-packages/drf_extra_fields/fields.py", line 221, in to_representation
    if value.isempty:
AttributeError: 'dict' object has no attribute 'isempty'
WARNING || 2020-09-19 13:53:03,085 || log || Not Found: /favicon.ico
ERROR || 2020-09-19 14:29:19,043 || log || Internal Server Error: /archives/tvseries/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 264, in data
    self._data = self.get_initial()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 410, in get_initial
    return OrderedDict([
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 411, in <listcomp>
    (field.field_name, field.get_initial())
  File "/usr/local/lib/python3.8/site-packages/drf_extra_fields/fields.py", line 231, in get_initial
    return self.to_representation(initial)
  File "/usr/local/lib/python3.8/site-packages/drf_extra_fields/fields.py", line 221, in to_representation
    if value.isempty:
AttributeError: 'dict' object has no attribute 'isempty'
ERROR || 2020-09-19 14:29:21,090 || log || Internal Server Error: /archives/tvseries/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 264, in data
    self._data = self.get_initial()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 410, in get_initial
    return OrderedDict([
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 411, in <listcomp>
    (field.field_name, field.get_initial())
  File "/usr/local/lib/python3.8/site-packages/drf_extra_fields/fields.py", line 231, in get_initial
    return self.to_representation(initial)
  File "/usr/local/lib/python3.8/site-packages/drf_extra_fields/fields.py", line 221, in to_representation
    if value.isempty:
AttributeError: 'dict' object has no attribute 'isempty'
WARNING || 2020-09-19 14:29:27,962 || log || Bad Request: /archives/tvseries/
ERROR || 2020-09-19 14:30:07,268 || log || Internal Server Error: /archives/tvseries/14/seasons/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 264, in data
    self._data = self.get_initial()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 410, in get_initial
    return OrderedDict([
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 411, in <listcomp>
    (field.field_name, field.get_initial())
  File "/usr/local/lib/python3.8/site-packages/drf_extra_fields/fields.py", line 231, in get_initial
    return self.to_representation(initial)
  File "/usr/local/lib/python3.8/site-packages/drf_extra_fields/fields.py", line 221, in to_representation
    if value.isempty:
AttributeError: 'dict' object has no attribute 'isempty'
ERROR || 2020-09-19 14:30:13,169 || log || Internal Server Error: /archives/tvseries/14/seasons/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 202, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/usr/local/lib/python3.8/site-packages/rest_framework/renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 264, in data
    self._data = self.get_initial()
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 410, in get_initial
    return OrderedDict([
  File "/usr/local/lib/python3.8/site-packages/rest_framework/serializers.py", line 411, in <listcomp>
    (field.field_name, field.get_initial())
  File "/usr/local/lib/python3.8/site-packages/drf_extra_fields/fields.py", line 231, in get_initial
    return self.to_representation(initial)
  File "/usr/local/lib/python3.8/site-packages/drf_extra_fields/fields.py", line 221, in to_representation
    if value.isempty:
AttributeError: 'dict' object has no attribute 'isempty'
WARNING || 2020-09-19 16:52:23,841 || log || Not Found: /favicon.ico
WARNING || 2020-09-19 20:54:13,506 || log || Not Found: /favicon.ico
WARNING || 2020-09-19 20:54:13,524 || basehttp || "GET /favicon.ico HTTP/1.1" 404 12392
WARNING || 2020-09-20 09:49:07,583 || log || Not Found: /favicon.ico
WARNING || 2020-09-20 09:49:07,610 || basehttp || "GET /favicon.ico HTTP/1.1" 404 12392
WARNING || 2020-09-20 10:20:02,166 || log || Not Found: /administration/history/tvseriesmodel/10000003/
WARNING || 2020-09-20 10:20:02,291 || log || Forbidden: /administration/history/tvseriesmodel/3/
WARNING || 2020-09-20 10:20:02,542 || log || Forbidden: /administration/logs/
WARNING || 2020-09-20 10:20:10,850 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-20 10:20:10,955 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-20 10:20:11,480 || log || Forbidden: /archives/tvseries/30/delete-image/8,9/
WARNING || 2020-09-20 10:20:11,691 || log || Forbidden: /archives/tvseries/30/delete-image/12,13/
WARNING || 2020-09-20 10:20:11,862 || log || Bad Request: /archives/tvseries/30/delete-image/1000,999/
WARNING || 2020-09-20 10:20:12,140 || log || Bad Request: /archives/tvseries/32/upload-image/small_image.gif/
WARNING || 2020-09-20 10:20:12,609 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-20 10:20:12,745 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-20 10:20:12,854 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-20 10:20:12,990 || log || Not Found: /archives/manage-permissions/1/
WARNING || 2020-09-20 10:20:13,080 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-20 10:20:13,178 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-20 10:20:13,294 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-20 10:20:13,378 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-20 10:20:14,011 || log || Not Found: /archives/tvseries/0/seasons/
WARNING || 2020-09-20 10:20:14,110 || log || Forbidden: /archives/tvseries/35/seasons/
WARNING || 2020-09-20 10:20:14,250 || log || Forbidden: /archives/tvseries/36/seasons/
WARNING || 2020-09-20 10:20:14,430 || log || Bad Request: /archives/tvseries/37/seasons/164/delete_subtitle/9999999999999/
WARNING || 2020-09-20 10:20:14,514 || log || Forbidden: /archives/tvseries/37/seasons/164/delete_subtitle/1/
WARNING || 2020-09-20 10:20:15,403 || log || Bad Request: /archives/tvseries/37/seasons/162/add_subtitle/
WARNING || 2020-09-20 10:20:15,485 || log || Forbidden: /archives/tvseries/37/seasons/162/add_subtitle/
WARNING || 2020-09-20 10:20:15,772 || log || Forbidden: /archives/tvseries/41/
WARNING || 2020-09-20 10:20:16,096 || log || Forbidden: /archives/tvseries/47/
WARNING || 2020-09-20 10:20:29,045 || log || Not Found: /archives/tvseries/999/upload-image/test.jpg/
WARNING || 2020-09-20 10:20:29,846 || log || Bad Request: /auth/users/
WARNING || 2020-09-20 10:20:30,469 || log || Bad Request: /auth/users/confirm_undelete_account/
WARNING || 2020-09-20 10:20:31,231 || log || Bad Request: /auth/users/
WARNING || 2020-09-20 10:20:31,316 || log || Bad Request: /auth/users/
WARNING || 2020-09-20 10:20:31,391 || log || Bad Request: /auth/users/
WARNING || 2020-09-20 10:20:31,686 || log || Bad Request: /auth/users/
WARNING || 2020-09-20 10:20:31,766 || log || Bad Request: /auth/users/
WARNING || 2020-09-20 10:20:32,360 || log || Bad Request: /auth/jwt/create
WARNING || 2020-09-20 10:20:32,751 || log || Forbidden: /auth/users/master_slave_interchange/
WARNING || 2020-09-20 10:20:33,754 || log || Too Many Requests: /auth/users/master_slave_interchange/
WARNING || 2020-09-20 10:20:34,077 || log || Bad Request: /auth/users/master_slave_interchange/
WARNING || 2020-09-20 10:20:34,317 || log || Bad Request: /auth/jwt/refresh
WARNING || 2020-09-20 10:20:34,400 || log || Unauthorized: /auth/jwt/refresh
WARNING || 2020-09-20 10:20:35,030 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-20 10:20:35,593 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-20 10:20:36,117 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-20 10:20:36,298 || log || Forbidden: /auth/users/resend_activation/
WARNING || 2020-09-20 10:20:36,375 || log || Forbidden: /auth/users/resend_activation/
WARNING || 2020-09-20 10:20:36,477 || log || Too Many Requests: /auth/users/resend_activation/
WARNING || 2020-09-20 10:20:37,097 || log || Too Many Requests: /auth/users/undelete_account/
WARNING || 2020-09-20 10:20:37,630 || log || Bad Request: /auth/users/undelete_account/
WARNING || 2020-09-20 16:25:26,350 || log || Forbidden: /archives/tvseries/full-text-search/
WARNING || 2020-09-20 16:25:26,362 || basehttp || "GET /archives/tvseries/full-text-search/ HTTP/1.1" 403 14317
WARNING || 2020-09-20 16:26:00,897 || log || Forbidden: /archives/tvseries/full-text-search/
WARNING || 2020-09-20 16:26:00,957 || basehttp || "GET /archives/tvseries/full-text-search/ HTTP/1.1" 403 14316
WARNING || 2020-09-20 16:26:02,148 || log || Forbidden: /archives/tvseries/full-text-search/
WARNING || 2020-09-20 16:26:02,314 || basehttp || "GET /archives/tvseries/full-text-search/ HTTP/1.1" 403 14316
WARNING || 2020-09-20 16:26:06,420 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-20 16:26:06,424 || basehttp || "GET /archives/tvseries/full-text-search/ HTTP/1.1" 400 15057
WARNING || 2020-09-21 10:55:31,933 || log || Not Found: /archives/tvseries/14/seasons/
WARNING || 2020-09-21 14:09:06,171 || log || Not Found: /administration/history/tvseriesmodel/10000003/
WARNING || 2020-09-21 14:09:06,265 || log || Forbidden: /administration/history/tvseriesmodel/3/
WARNING || 2020-09-21 14:09:06,565 || log || Forbidden: /administration/logs/
WARNING || 2020-09-21 14:09:14,672 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-21 14:09:14,742 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-21 14:09:15,163 || log || Forbidden: /archives/tvseries/30/delete-image/8,9/
WARNING || 2020-09-21 14:09:15,263 || log || Forbidden: /archives/tvseries/30/delete-image/12,13/
WARNING || 2020-09-21 14:09:15,356 || log || Bad Request: /archives/tvseries/30/delete-image/1000,999/
WARNING || 2020-09-21 14:09:15,547 || log || Bad Request: /archives/tvseries/32/upload-image/small_image.gif/
WARNING || 2020-09-21 14:09:15,985 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-21 14:09:16,075 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-21 14:09:16,156 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-21 14:09:16,265 || log || Not Found: /archives/manage-permissions/1/
WARNING || 2020-09-21 14:09:16,351 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-21 14:09:16,431 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-21 14:09:16,509 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-21 14:09:16,586 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-21 14:09:17,151 || log || Not Found: /archives/tvseries/0/seasons/
WARNING || 2020-09-21 14:09:17,224 || log || Forbidden: /archives/tvseries/35/seasons/
WARNING || 2020-09-21 14:09:17,344 || log || Forbidden: /archives/tvseries/36/seasons/
WARNING || 2020-09-21 14:09:17,485 || log || Bad Request: /archives/tvseries/37/seasons/164/delete_subtitle/9999999999999/
WARNING || 2020-09-21 14:09:17,561 || log || Forbidden: /archives/tvseries/37/seasons/164/delete_subtitle/1/
WARNING || 2020-09-21 14:09:18,403 || log || Bad Request: /archives/tvseries/37/seasons/162/add_subtitle/
WARNING || 2020-09-21 14:09:18,472 || log || Forbidden: /archives/tvseries/37/seasons/162/add_subtitle/
WARNING || 2020-09-21 14:09:18,724 || log || Forbidden: /archives/tvseries/41/
WARNING || 2020-09-21 14:09:19,005 || log || Forbidden: /archives/tvseries/47/
WARNING || 2020-09-21 14:09:32,463 || log || Not Found: /archives/tvseries/999/upload-image/test.jpg/
WARNING || 2020-09-21 14:09:33,532 || log || Bad Request: /auth/users/
WARNING || 2020-09-21 14:09:34,547 || log || Bad Request: /auth/users/confirm_undelete_account/
WARNING || 2020-09-21 14:09:36,913 || log || Bad Request: /auth/users/
WARNING || 2020-09-21 14:09:37,121 || log || Bad Request: /auth/users/
WARNING || 2020-09-21 14:09:37,357 || log || Bad Request: /auth/users/
WARNING || 2020-09-21 14:09:38,432 || log || Bad Request: /auth/users/
WARNING || 2020-09-21 14:09:38,673 || log || Bad Request: /auth/users/
WARNING || 2020-09-21 14:09:39,888 || log || Bad Request: /auth/jwt/create
WARNING || 2020-09-21 14:09:40,840 || log || Forbidden: /auth/users/master_slave_interchange/
WARNING || 2020-09-21 14:09:43,569 || log || Too Many Requests: /auth/users/master_slave_interchange/
WARNING || 2020-09-21 14:09:44,452 || log || Bad Request: /auth/users/master_slave_interchange/
WARNING || 2020-09-21 14:09:44,893 || log || Bad Request: /auth/jwt/refresh
WARNING || 2020-09-21 14:09:45,069 || log || Unauthorized: /auth/jwt/refresh
WARNING || 2020-09-21 14:09:46,505 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-21 14:09:47,219 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-21 14:09:48,091 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-21 14:09:48,295 || log || Forbidden: /auth/users/resend_activation/
WARNING || 2020-09-21 14:09:48,403 || log || Forbidden: /auth/users/resend_activation/
WARNING || 2020-09-21 14:09:48,546 || log || Too Many Requests: /auth/users/resend_activation/
WARNING || 2020-09-21 14:09:49,494 || log || Too Many Requests: /auth/users/undelete_account/
WARNING || 2020-09-21 14:09:50,393 || log || Bad Request: /auth/users/undelete_account/
WARNING || 2020-09-21 11:34:43,958 || log || Not Found: /administration/history/tvseriesmodel/10000003/
WARNING || 2020-09-21 11:34:44,534 || log || Forbidden: /administration/history/tvseriesmodel/3/
WARNING || 2020-09-21 11:34:45,137 || log || Forbidden: /administration/logs/
WARNING || 2020-09-21 11:35:02,162 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-21 11:35:02,894 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-21 11:35:03,786 || log || Forbidden: /archives/tvseries/30/delete-image/8,9/
WARNING || 2020-09-21 11:35:04,440 || log || Forbidden: /archives/tvseries/30/delete-image/12,13/
WARNING || 2020-09-21 11:35:05,091 || log || Bad Request: /archives/tvseries/30/delete-image/1000,999/
WARNING || 2020-09-21 11:35:05,723 || log || Bad Request: /archives/tvseries/32/upload-image/small_image.gif/
WARNING || 2020-09-21 11:35:06,593 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-21 11:35:07,180 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-21 11:35:07,780 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-21 11:35:08,418 || log || Not Found: /archives/manage-permissions/1/
WARNING || 2020-09-21 11:35:09,007 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-21 11:35:09,538 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-21 11:35:10,092 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-21 11:35:10,642 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-21 11:35:11,553 || log || Not Found: /archives/tvseries/0/seasons/
WARNING || 2020-09-21 11:35:12,180 || log || Forbidden: /archives/tvseries/35/seasons/
WARNING || 2020-09-21 11:35:12,729 || log || Forbidden: /archives/tvseries/36/seasons/
WARNING || 2020-09-21 11:35:13,280 || log || Bad Request: /archives/tvseries/37/seasons/164/delete_subtitle/9999999999999/
WARNING || 2020-09-21 11:35:13,813 || log || Forbidden: /archives/tvseries/37/seasons/164/delete_subtitle/1/
WARNING || 2020-09-21 11:35:14,781 || log || Bad Request: /archives/tvseries/37/seasons/162/add_subtitle/
WARNING || 2020-09-21 11:35:15,339 || log || Forbidden: /archives/tvseries/37/seasons/162/add_subtitle/
WARNING || 2020-09-21 11:35:15,951 || log || Forbidden: /archives/tvseries/41/
WARNING || 2020-09-21 11:35:17,649 || log || Forbidden: /archives/tvseries/47/
WARNING || 2020-09-21 11:35:49,716 || log || Not Found: /archives/tvseries/999/upload-image/test.jpg/
WARNING || 2020-09-21 11:35:50,697 || log || Bad Request: /auth/users/
WARNING || 2020-09-21 11:35:51,500 || log || Bad Request: /auth/users/confirm_undelete_account/
WARNING || 2020-09-21 11:35:52,280 || log || Bad Request: /auth/users/
WARNING || 2020-09-21 11:35:52,807 || log || Bad Request: /auth/users/
WARNING || 2020-09-21 11:35:53,367 || log || Bad Request: /auth/users/
WARNING || 2020-09-21 11:35:54,021 || log || Bad Request: /auth/users/
WARNING || 2020-09-21 11:35:54,578 || log || Bad Request: /auth/users/
WARNING || 2020-09-21 11:35:55,362 || log || Bad Request: /auth/jwt/create
WARNING || 2020-09-21 11:35:56,008 || log || Forbidden: /auth/users/master_slave_interchange/
WARNING || 2020-09-21 11:35:57,030 || log || Too Many Requests: /auth/users/master_slave_interchange/
WARNING || 2020-09-21 11:35:57,676 || log || Bad Request: /auth/users/master_slave_interchange/
WARNING || 2020-09-21 11:35:58,365 || log || Bad Request: /auth/jwt/refresh
WARNING || 2020-09-21 11:35:58,955 || log || Unauthorized: /auth/jwt/refresh
WARNING || 2020-09-21 11:35:59,791 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-21 11:36:00,682 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-21 11:36:01,564 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-21 11:36:02,151 || log || Forbidden: /auth/users/resend_activation/
WARNING || 2020-09-21 11:36:02,776 || log || Forbidden: /auth/users/resend_activation/
WARNING || 2020-09-21 11:36:03,415 || log || Too Many Requests: /auth/users/resend_activation/
WARNING || 2020-09-21 11:36:04,228 || log || Too Many Requests: /auth/users/undelete_account/
WARNING || 2020-09-21 11:36:05,215 || log || Bad Request: /auth/users/undelete_account/
WARNING || 2020-09-27 09:47:45,073 || log || Not Found: /administration/history/tvseriesmodel/10000003/
WARNING || 2020-09-27 09:47:45,203 || log || Forbidden: /administration/history/tvseriesmodel/3/
WARNING || 2020-09-27 09:47:45,450 || log || Forbidden: /administration/logs/
WARNING || 2020-09-27 09:47:53,431 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-27 09:47:53,510 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-27 09:47:53,846 || log || Forbidden: /archives/tvseries/30/delete-image/8,9/
WARNING || 2020-09-27 09:47:53,965 || log || Forbidden: /archives/tvseries/30/delete-image/12,13/
WARNING || 2020-09-27 09:47:54,062 || log || Bad Request: /archives/tvseries/30/delete-image/1000,999/
WARNING || 2020-09-27 09:47:54,214 || log || Bad Request: /archives/tvseries/32/upload-image/small_image.gif/
WARNING || 2020-09-27 09:47:54,632 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-27 09:47:54,733 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-27 09:47:54,827 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-27 09:47:54,927 || log || Not Found: /archives/manage-permissions/1/
WARNING || 2020-09-27 09:47:55,014 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-27 09:47:55,097 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-27 09:47:55,178 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-27 09:47:55,261 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-27 09:47:55,773 || log || Not Found: /archives/tvseries/0/seasons/
WARNING || 2020-09-27 09:47:55,846 || log || Forbidden: /archives/tvseries/35/seasons/
WARNING || 2020-09-27 09:47:55,969 || log || Forbidden: /archives/tvseries/36/seasons/
WARNING || 2020-09-27 09:47:56,129 || log || Bad Request: /archives/tvseries/37/seasons/164/delete_subtitle/9999999999999/
WARNING || 2020-09-27 09:47:56,201 || log || Forbidden: /archives/tvseries/37/seasons/164/delete_subtitle/1/
WARNING || 2020-09-27 09:47:57,137 || log || Bad Request: /archives/tvseries/37/seasons/162/add_subtitle/
WARNING || 2020-09-27 09:47:57,213 || log || Forbidden: /archives/tvseries/37/seasons/162/add_subtitle/
WARNING || 2020-09-27 09:47:57,478 || log || Forbidden: /archives/tvseries/41/
WARNING || 2020-09-27 09:47:57,801 || log || Forbidden: /archives/tvseries/47/
WARNING || 2020-09-27 09:48:12,150 || log || Not Found: /archives/tvseries/999/upload-image/test.jpg/
WARNING || 2020-09-27 09:48:13,253 || log || Bad Request: /auth/users/
WARNING || 2020-09-27 09:48:14,041 || log || Bad Request: /auth/users/confirm_undelete_account/
WARNING || 2020-09-27 09:48:14,981 || log || Bad Request: /auth/users/
WARNING || 2020-09-27 09:48:15,123 || log || Bad Request: /auth/users/
WARNING || 2020-09-27 09:48:15,270 || log || Bad Request: /auth/users/
WARNING || 2020-09-27 09:48:15,726 || log || Bad Request: /auth/users/
WARNING || 2020-09-27 09:48:15,835 || log || Bad Request: /auth/users/
WARNING || 2020-09-27 09:48:16,466 || log || Bad Request: /auth/jwt/create
WARNING || 2020-09-27 09:48:16,845 || log || Forbidden: /auth/users/master_slave_interchange/
WARNING || 2020-09-27 09:48:17,800 || log || Too Many Requests: /auth/users/master_slave_interchange/
WARNING || 2020-09-27 09:48:18,092 || log || Bad Request: /auth/users/master_slave_interchange/
WARNING || 2020-09-27 09:48:18,227 || log || Bad Request: /auth/jwt/refresh
WARNING || 2020-09-27 09:48:18,309 || log || Unauthorized: /auth/jwt/refresh
WARNING || 2020-09-27 09:48:18,971 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-27 09:48:19,496 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-27 09:48:20,004 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-09-27 09:48:20,146 || log || Forbidden: /auth/users/resend_activation/
WARNING || 2020-09-27 09:48:20,221 || log || Forbidden: /auth/users/resend_activation/
WARNING || 2020-09-27 09:48:20,330 || log || Too Many Requests: /auth/users/resend_activation/
WARNING || 2020-09-27 09:48:20,943 || log || Too Many Requests: /auth/users/undelete_account/
WARNING || 2020-09-27 09:48:21,448 || log || Bad Request: /auth/users/undelete_account/
WARNING || 2020-09-30 21:16:50,435 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-30 21:16:50,595 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-30 21:16:51,857 || log || Forbidden: /archives/tvseries/7/delete-image/2,3/
WARNING || 2020-09-30 21:16:51,964 || log || Forbidden: /archives/tvseries/7/delete-image/6,7/
WARNING || 2020-09-30 21:16:52,068 || log || Bad Request: /archives/tvseries/7/delete-image/1000,999/
WARNING || 2020-09-30 21:16:52,322 || log || Bad Request: /archives/tvseries/9/upload-image/small_image.gif/
WARNING || 2020-09-30 21:16:52,930 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:16:53,070 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:16:53,168 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:16:53,275 || log || Not Found: /archives/manage-permissions/1/
WARNING || 2020-09-30 21:16:53,363 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:16:53,458 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:16:53,552 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:16:53,631 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:16:54,238 || log || Not Found: /archives/tvseries/0/seasons/
WARNING || 2020-09-30 21:16:54,319 || log || Forbidden: /archives/tvseries/35/seasons/
WARNING || 2020-09-30 21:16:54,444 || log || Forbidden: /archives/tvseries/36/seasons/
WARNING || 2020-09-30 21:16:54,604 || log || Bad Request: /archives/tvseries/37/seasons/131/delete_subtitle/9999999999999/
WARNING || 2020-09-30 21:16:54,677 || log || Forbidden: /archives/tvseries/37/seasons/131/delete_subtitle/1/
WARNING || 2020-09-30 21:16:55,469 || log || Bad Request: /archives/tvseries/37/seasons/129/add_subtitle/
WARNING || 2020-09-30 21:16:55,542 || log || Forbidden: /archives/tvseries/37/seasons/129/add_subtitle/
WARNING || 2020-09-30 21:16:55,790 || log || Forbidden: /archives/tvseries/41/
WARNING || 2020-09-30 21:16:56,182 || log || Forbidden: /archives/tvseries/47/
ERROR || 2020-09-30 21:17:03,474 || log || Internal Server Error: /archives/tvseries/43/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\generics.py", line 288, in patch
    return self.partial_update(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\mixins.py", line 82, in partial_update
    return self.update(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\mixins.py", line 68, in update
    self.perform_update(serializer)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\mixins.py", line 78, in perform_update
    serializer.save()
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "c:\python\lib\contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "C:\Users\hardcase1\PycharmProjects\series\archives\serializers.py", line 181, in update
    to_delete = set(qs).difference(list_of_interrelationships)
  File "C:\Users\hardcase1\PycharmProjects\series\archives\models.py", line 86, in __hash__
    return functools.reduce(operator.xor, (self.from_series_id, self.from_series_id, self.reason_for_interrelationship))
TypeError: unsupported operand type(s) for ^: 'int' and 'str'
ERROR || 2020-09-30 21:17:04,767 || log || Internal Server Error: /archives/tvseries/49/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\generics.py", line 285, in put
    return self.update(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\mixins.py", line 68, in update
    self.perform_update(serializer)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\mixins.py", line 78, in perform_update
    serializer.save()
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\serializers.py", line 207, in save
    self.instance = self.update(self.instance, validated_data)
  File "c:\python\lib\contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "C:\Users\hardcase1\PycharmProjects\series\archives\serializers.py", line 181, in update
    to_delete = set(qs).difference(list_of_interrelationships)
  File "C:\Users\hardcase1\PycharmProjects\series\archives\models.py", line 86, in __hash__
    return functools.reduce(operator.xor, (self.from_series_id, self.from_series_id, self.reason_for_interrelationship))
TypeError: unsupported operand type(s) for ^: 'int' and 'str'
WARNING || 2020-09-30 21:18:08,437 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-30 21:18:08,551 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-30 21:18:09,782 || log || Forbidden: /archives/tvseries/7/delete-image/2,3/
WARNING || 2020-09-30 21:18:09,929 || log || Forbidden: /archives/tvseries/7/delete-image/6,7/
WARNING || 2020-09-30 21:18:10,053 || log || Bad Request: /archives/tvseries/7/delete-image/1000,999/
WARNING || 2020-09-30 21:18:10,221 || log || Bad Request: /archives/tvseries/9/upload-image/small_image.gif/
WARNING || 2020-09-30 21:18:10,786 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:18:10,950 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:18:11,064 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:18:11,198 || log || Not Found: /archives/manage-permissions/1/
WARNING || 2020-09-30 21:18:11,317 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:18:11,427 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:18:11,539 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:18:11,648 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:18:12,364 || log || Not Found: /archives/tvseries/0/seasons/
WARNING || 2020-09-30 21:18:12,485 || log || Forbidden: /archives/tvseries/35/seasons/
WARNING || 2020-09-30 21:18:12,645 || log || Forbidden: /archives/tvseries/36/seasons/
WARNING || 2020-09-30 21:18:12,840 || log || Bad Request: /archives/tvseries/37/seasons/131/delete_subtitle/9999999999999/
WARNING || 2020-09-30 21:18:12,931 || log || Forbidden: /archives/tvseries/37/seasons/131/delete_subtitle/1/
WARNING || 2020-09-30 21:18:13,404 || log || Bad Request: /archives/tvseries/37/seasons/129/add_subtitle/
WARNING || 2020-09-30 21:18:13,480 || log || Forbidden: /archives/tvseries/37/seasons/129/add_subtitle/
WARNING || 2020-09-30 21:18:13,756 || log || Forbidden: /archives/tvseries/41/
WARNING || 2020-09-30 21:18:14,105 || log || Forbidden: /archives/tvseries/47/
WARNING || 2020-09-30 21:24:26,908 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-30 21:24:26,984 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-09-30 21:24:27,971 || log || Forbidden: /archives/tvseries/7/delete-image/2,3/
WARNING || 2020-09-30 21:24:28,082 || log || Forbidden: /archives/tvseries/7/delete-image/6,7/
WARNING || 2020-09-30 21:24:28,182 || log || Bad Request: /archives/tvseries/7/delete-image/1000,999/
WARNING || 2020-09-30 21:24:28,324 || log || Bad Request: /archives/tvseries/9/upload-image/small_image.gif/
WARNING || 2020-09-30 21:24:28,790 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:24:28,947 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:24:29,044 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:24:29,158 || log || Not Found: /archives/manage-permissions/1/
WARNING || 2020-09-30 21:24:29,259 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:24:29,348 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:24:29,444 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:24:29,533 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-09-30 21:24:30,057 || log || Not Found: /archives/tvseries/0/seasons/
WARNING || 2020-09-30 21:24:30,136 || log || Forbidden: /archives/tvseries/35/seasons/
WARNING || 2020-09-30 21:24:30,218 || log || Forbidden: /archives/tvseries/36/seasons/
WARNING || 2020-09-30 21:24:30,418 || log || Bad Request: /archives/tvseries/37/seasons/131/delete_subtitle/9999999999999/
WARNING || 2020-09-30 21:24:30,492 || log || Forbidden: /archives/tvseries/37/seasons/131/delete_subtitle/1/
WARNING || 2020-09-30 21:24:30,955 || log || Bad Request: /archives/tvseries/37/seasons/129/add_subtitle/
WARNING || 2020-09-30 21:24:31,028 || log || Forbidden: /archives/tvseries/37/seasons/129/add_subtitle/
WARNING || 2020-09-30 21:24:31,275 || log || Forbidden: /archives/tvseries/41/
WARNING || 2020-09-30 21:24:31,583 || log || Forbidden: /archives/tvseries/47/
WARNING || 2020-10-07 14:37:08,888 || log || Not Found: /
WARNING || 2020-10-07 14:37:08,955 || basehttp || "GET / HTTP/1.1" 404 12560
WARNING || 2020-10-07 14:37:11,099 || log || Not Found: /favicon.ico
WARNING || 2020-10-07 14:37:11,779 || basehttp || "GET /favicon.ico HTTP/1.1" 404 12609
WARNING || 2020-10-07 14:37:20,158 || log || Not Found: /swager
WARNING || 2020-10-07 14:37:20,169 || basehttp || "GET /swager HTTP/1.1" 404 12594
WARNING || 2020-10-07 14:37:26,331 || log || Forbidden: /swagger/
WARNING || 2020-10-07 14:37:26,334 || basehttp || "GET /swagger/ HTTP/1.1" 403 13
WARNING || 2020-10-07 14:37:29,511 || log || Forbidden: /swagger/
WARNING || 2020-10-07 14:37:29,521 || basehttp || "GET /swagger/ HTTP/1.1" 403 13
WARNING || 2020-10-07 14:37:40,245 || log || Forbidden: /redoc/
WARNING || 2020-10-07 14:37:40,247 || basehttp || "GET /redoc/ HTTP/1.1" 403 13
WARNING || 2020-10-07 14:38:05,171 || log || Forbidden: /swagger/
WARNING || 2020-10-07 14:38:05,273 || basehttp || "GET /swagger/ HTTP/1.1" 403 13
WARNING || 2020-10-07 14:39:37,712 || log || Forbidden: /swagger/
WARNING || 2020-10-07 14:39:37,725 || basehttp || "GET /swagger/ HTTP/1.1" 403 13
ERROR || 2020-10-07 14:39:44,927 || log || Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 202, in _get_response
    response = response.render()
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\users\hardcase1\.virtualenvs\series-eaob5ihd\src\drf-yasg2\src\drf_yasg\renderers.py", line 75, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg2/swagger-ui.html
ERROR || 2020-10-07 14:39:45,049 || basehttp || "GET /swagger/ HTTP/1.1" 500 123707
WARNING || 2020-10-08 14:45:43,345 || log || Not Found: /administration/history/tvseriesmodel/10000003/
WARNING || 2020-10-08 14:45:43,450 || log || Forbidden: /administration/history/tvseriesmodel/3/
WARNING || 2020-10-08 14:45:43,692 || log || Forbidden: /administration/logs/
WARNING || 2020-10-08 14:45:50,802 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-10-08 14:45:50,876 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-10-08 14:45:51,240 || log || Forbidden: /archives/tvseries/30/delete-image/8,9/
WARNING || 2020-10-08 14:45:51,330 || log || Forbidden: /archives/tvseries/30/delete-image/12,13/
WARNING || 2020-10-08 14:45:51,408 || log || Bad Request: /archives/tvseries/30/delete-image/1000,999/
WARNING || 2020-10-08 14:45:51,636 || log || Bad Request: /archives/tvseries/32/upload-image/small_image.gif/
WARNING || 2020-10-08 14:45:52,158 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-10-08 14:45:52,231 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-10-08 14:45:52,325 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-10-08 14:45:52,422 || log || Not Found: /archives/manage-permissions/1/
WARNING || 2020-10-08 14:45:52,502 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-10-08 14:45:52,581 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-10-08 14:45:52,642 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-10-08 14:45:52,726 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-10-08 14:45:53,271 || log || Not Found: /archives/tvseries/0/seasons/
WARNING || 2020-10-08 14:45:53,341 || log || Forbidden: /archives/tvseries/35/seasons/
WARNING || 2020-10-08 14:45:53,471 || log || Forbidden: /archives/tvseries/36/seasons/
WARNING || 2020-10-08 14:45:53,639 || log || Bad Request: /archives/tvseries/37/seasons/164/delete_subtitle/9999999999999/
WARNING || 2020-10-08 14:45:53,693 || log || Forbidden: /archives/tvseries/37/seasons/164/delete_subtitle/1/
WARNING || 2020-10-08 14:45:54,481 || log || Bad Request: /archives/tvseries/37/seasons/162/add_subtitle/
WARNING || 2020-10-08 14:45:54,546 || log || Forbidden: /archives/tvseries/37/seasons/162/add_subtitle/
WARNING || 2020-10-08 14:45:54,798 || log || Forbidden: /archives/tvseries/41/
WARNING || 2020-10-08 14:45:55,042 || log || Forbidden: /archives/tvseries/47/
WARNING || 2020-10-08 14:46:07,590 || log || Not Found: /archives/tvseries/999/upload-image/test.jpg/
WARNING || 2020-10-08 14:46:08,047 || log || Bad Request: /auth/users/
WARNING || 2020-10-08 14:46:08,521 || log || Bad Request: /auth/users/confirm_undelete_account/
WARNING || 2020-10-08 14:46:09,021 || log || Bad Request: /auth/users/
WARNING || 2020-10-08 14:46:09,086 || log || Bad Request: /auth/users/
WARNING || 2020-10-08 14:46:09,142 || log || Bad Request: /auth/users/
WARNING || 2020-10-08 14:46:09,339 || log || Bad Request: /auth/users/
WARNING || 2020-10-08 14:46:09,404 || log || Bad Request: /auth/users/
WARNING || 2020-10-08 14:46:09,790 || log || Bad Request: /auth/jwt/create
ERROR || 2020-10-08 14:46:10,069 || log || Internal Server Error: /auth/users/master_slave_interchange/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
TypeError: permission_denied() got an unexpected keyword argument 'code'
WARNING || 2020-10-08 14:46:10,658 || log || Too Many Requests: /auth/users/master_slave_interchange/
WARNING || 2020-10-08 14:46:10,850 || log || Bad Request: /auth/users/master_slave_interchange/
WARNING || 2020-10-08 14:46:11,069 || log || Bad Request: /auth/jwt/refresh
WARNING || 2020-10-08 14:46:11,137 || log || Unauthorized: /auth/jwt/refresh
WARNING || 2020-10-08 14:46:11,529 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-10-08 14:46:11,860 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-10-08 14:46:12,172 || log || Bad Request: /auth/users/set_slaves/
ERROR || 2020-10-08 14:46:12,302 || log || Internal Server Error: /auth/users/resend_activation/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
TypeError: permission_denied() got an unexpected keyword argument 'code'
ERROR || 2020-10-08 14:46:12,381 || log || Internal Server Error: /auth/users/resend_activation/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
TypeError: permission_denied() got an unexpected keyword argument 'code'
WARNING || 2020-10-08 14:46:12,475 || log || Too Many Requests: /auth/users/resend_activation/
WARNING || 2020-10-08 14:46:12,877 || log || Too Many Requests: /auth/users/undelete_account/
WARNING || 2020-10-08 14:46:13,208 || log || Bad Request: /auth/users/undelete_account/
ERROR || 2020-10-08 14:47:11,857 || log || Internal Server Error: /auth/users/resend_activation/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
TypeError: permission_denied() got an unexpected keyword argument 'code'
ERROR || 2020-10-08 14:48:33,482 || log || Internal Server Error: /auth/users/resend_activation/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
TypeError: permission_denied() got an unexpected keyword argument 'code'
WARNING || 2020-10-08 14:49:25,448 || log || Not Found: /administration/history/tvseriesmodel/10000003/
WARNING || 2020-10-08 14:49:25,546 || log || Forbidden: /administration/history/tvseriesmodel/3/
WARNING || 2020-10-08 14:49:25,774 || log || Forbidden: /administration/logs/
WARNING || 2020-10-08 14:49:32,232 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-10-08 14:49:32,307 || log || Bad Request: /archives/tvseries/full-text-search/
WARNING || 2020-10-08 14:49:32,642 || log || Forbidden: /archives/tvseries/30/delete-image/8,9/
WARNING || 2020-10-08 14:49:32,752 || log || Forbidden: /archives/tvseries/30/delete-image/12,13/
WARNING || 2020-10-08 14:49:32,837 || log || Bad Request: /archives/tvseries/30/delete-image/1000,999/
WARNING || 2020-10-08 14:49:32,974 || log || Bad Request: /archives/tvseries/32/upload-image/small_image.gif/
WARNING || 2020-10-08 14:49:33,570 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-10-08 14:49:33,662 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-10-08 14:49:33,763 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-10-08 14:49:33,884 || log || Not Found: /archives/manage-permissions/1/
WARNING || 2020-10-08 14:49:33,973 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-10-08 14:49:34,056 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-10-08 14:49:34,140 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-10-08 14:49:34,228 || log || Bad Request: /archives/manage-permissions/
WARNING || 2020-10-08 14:49:34,724 || log || Not Found: /archives/tvseries/0/seasons/
WARNING || 2020-10-08 14:49:34,806 || log || Forbidden: /archives/tvseries/35/seasons/
WARNING || 2020-10-08 14:49:34,943 || log || Forbidden: /archives/tvseries/36/seasons/
WARNING || 2020-10-08 14:49:35,140 || log || Bad Request: /archives/tvseries/37/seasons/164/delete_subtitle/9999999999999/
WARNING || 2020-10-08 14:49:35,193 || log || Forbidden: /archives/tvseries/37/seasons/164/delete_subtitle/1/
WARNING || 2020-10-08 14:49:35,625 || log || Bad Request: /archives/tvseries/37/seasons/162/add_subtitle/
WARNING || 2020-10-08 14:49:35,672 || log || Forbidden: /archives/tvseries/37/seasons/162/add_subtitle/
WARNING || 2020-10-08 14:49:35,920 || log || Forbidden: /archives/tvseries/41/
WARNING || 2020-10-08 14:49:36,207 || log || Forbidden: /archives/tvseries/47/
WARNING || 2020-10-08 14:49:47,965 || log || Not Found: /archives/tvseries/999/upload-image/test.jpg/
WARNING || 2020-10-08 14:49:48,460 || log || Bad Request: /auth/users/
WARNING || 2020-10-08 14:49:48,928 || log || Bad Request: /auth/users/confirm_undelete_account/
WARNING || 2020-10-08 14:49:49,308 || log || Bad Request: /auth/users/
WARNING || 2020-10-08 14:49:49,370 || log || Bad Request: /auth/users/
WARNING || 2020-10-08 14:49:49,423 || log || Bad Request: /auth/users/
WARNING || 2020-10-08 14:49:49,607 || log || Bad Request: /auth/users/
WARNING || 2020-10-08 14:49:49,662 || log || Bad Request: /auth/users/
WARNING || 2020-10-08 14:49:50,051 || log || Bad Request: /auth/jwt/create
ERROR || 2020-10-08 14:49:50,323 || log || Internal Server Error: /auth/users/master_slave_interchange/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
TypeError: permission_denied() got an unexpected keyword argument 'code'
WARNING || 2020-10-08 14:49:50,902 || log || Too Many Requests: /auth/users/master_slave_interchange/
WARNING || 2020-10-08 14:49:51,092 || log || Bad Request: /auth/users/master_slave_interchange/
WARNING || 2020-10-08 14:49:51,227 || log || Bad Request: /auth/jwt/refresh
WARNING || 2020-10-08 14:49:51,296 || log || Unauthorized: /auth/jwt/refresh
WARNING || 2020-10-08 14:49:51,880 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-10-08 14:49:52,177 || log || Bad Request: /auth/users/set_slaves/
WARNING || 2020-10-08 14:49:52,502 || log || Bad Request: /auth/users/set_slaves/
ERROR || 2020-10-08 14:49:52,623 || log || Internal Server Error: /auth/users/resend_activation/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
TypeError: permission_denied() got an unexpected keyword argument 'code'
ERROR || 2020-10-08 14:49:52,687 || log || Internal Server Error: /auth/users/resend_activation/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\views.py", line 333, in check_permissions
    self.permission_denied(
TypeError: permission_denied() got an unexpected keyword argument 'code'
WARNING || 2020-10-08 14:49:52,802 || log || Too Many Requests: /auth/users/resend_activation/
WARNING || 2020-10-08 14:49:53,253 || log || Too Many Requests: /auth/users/undelete_account/
WARNING || 2020-10-08 14:49:53,587 || log || Bad Request: /auth/users/undelete_account/
ERROR || 2020-10-08 15:19:58,186 || log || Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\core\handlers\base.py", line 202, in _get_response
    response = response.render()
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "c:\users\hardcase1\.virtualenvs\series-eaob5ihd\src\drf-yasg2\src\drf_yasg\renderers.py", line 75, in render
    return render_to_string(self.template, renderer_context, renderer_context['request'])
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\hardcase1\.virtualenvs\series-EAOB5IHD\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: drf-yasg2/swagger-ui.html
ERROR || 2020-10-08 15:19:58,312 || basehttp || "GET /swagger/ HTTP/1.1" 500 123701
